deploy:
  stage: production
  image: lwolf/helm-kubectl-docker
  before_script:
    - sed -i "s~<VERSION>~${CI_COMMIT_TAG}~g" .helm/Chart.yaml
  script:
    - helm upgrade crm-chart .helm --namespace "${KUBE_NAMESPACE}" --install
  environment:
    name: production
  when: manual
  only:
    - tags
  except:
    - branches
